default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 25
  username: postgres
  password: postgres

development:
  <<: *default
  database: online_shopping_store_development

test:
  <<: *default
  database: online_shopping_store_test

production:
  <<: *default
  database: 
  username: 
  password: <%= ENV['ONLINE_SHOPPING_STORE_DATABASE_PASSWORD'] %>
