# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b17ea8973d2db6481364a3f5a6ff15351bf3161520c8f334e262ac3697605064f7b491894f7b2eeca92514a4aab24158ef15b9cc447e98f0f145589d423c52
  domain_name: http://localhost:3000/
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>

test:
  secret_key_base: a26773092e832989a55e48a58b6b1fa9df9f1b8b58369a23abb5094298ac01ce3fa73d2619beffbbdb925bd854b735e3bf688cf6d31187056a8b31df47f80630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
